apiVersion: v1
kind: Service
metadata:
  name: des-retriever
spec:
  clusterIP: None
  selector:
    app: des-retriever
  ports:
    - port: 8001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: des-retriever-0
spec:
  selector:
    app: des-retriever
    statefulset.kubernetes.io/pod-name: des-retriever-0
  ports:
    - port: 8001
      targetPort: 8001
